CREATE PROCEDURE USP_ST_INPUT_CLIENT

AS
-----------------------------
-- Verify IF the Schemas exist
-----------------------------

IF OBJECT_ID('ST_CLIENTES') IS NOT NULL DROP TABLE ST_CLIENTES

	CREATE TABLE ST_CLIENTES
	(
	COD_CLIENTE		NUMERIC(15),
	NOME			VARCHAR(100),
	NOME_FANTASIA	VARCHAR(60),
	COD_CLASSIFICAO	NUMERIC(15)
	)

IF OBJECT_ID('ST_CLASSIFICAO_CLIENTES') IS NOT NULL DROP TABLE ST_CLASSIFICAO_CLIENTES

	CREATE TABLE ST_CLASSIFICAO_CLIENTES
	(
	COD_CLASSIFICAO NUMERIC(15),
	DESCRICAO		VARCHAR(100)
	)

IF OBJECT_ID('ST_ENDERECOS') IS NOT NULL DROP TABLE ST_ENDERECOS

	CREATE TABLE ST_ENDERECOS
	(
	COD_CLIENTE NUMERIC(15),
	CIDADE		VARCHAR(100),
	UF			VARCHAR(10),
	ESTADO		VARCHAR(100)
	)

-----------------------------
-- Clean the Stage Area
-----------------------------
TRUNCATE TABLE ST_CLIENTES
TRUNCATE TABLE ST_CLASSIFICAO_CLIENTES
TRUNCATE TABLE ST_ENDERECOS


-----------------------------
-- Insert Into Tables
-----------------------------
INSERT INTO ST_CLIENTES
	(
	COD_CLIENTE,
	NOME,
	NOME_FANTASIA,
	COD_CLASSIFICAO
	)

select A.ENTIDADE,
	   A.NOME,
	   A.NOME_FANTASIA,
	   A.CLASSIFICACAO_CLIENTE
from PBS_PROCFIT_DADOS.dbo.ENTIDADES A




INSERT INTO ST_CLASSIFICAO_CLIENTES
	(
	COD_CLASSIFICAO,
	DESCRICAO
	)

SELECT 
CLASSIFICACAO_CLIENTE,
DESCRICAO
FROM PBS_PROCFIT_DADOS.dbo.CLASSIFICACOES_CLIENTES



INSERT INTO ST_ENDERECOS
	(
	COD_CLIENTE,
	CIDADE,
	UF,
	ESTADO
	)

SELECT  A.ENTIDADE,
		A.CIDADE,
		B.ESTADO,
		B.NOME AS 'NOME ESTADO'
FROM PBS_PROCFIT_DADOS.dbo.ENDERECOS A
	LEFT JOIN PBS_PROCFIT_DADOS.DBO.ESTADOS B 
	ON A.ESTADO = B.ESTADO
